### ISSUE TITLE
contact details

### ISSUE THREAD

**Issue by yamin8000** [surbiks/xray-docker#1]
Hi
How can I contact you?

**Comment by surbiks** [comment]
hi
why? you can ask me any question here.

**Comment by yamin8000** [comment]
> hi why? you can ask me any question here.

It's related to one of your projects that is not on GitHub. A text-to-picture app.

**Comment by surbiks** [comment]
> > hi why? you can ask me any question here.
> 
> It's related to one of your projects that is not on GitHub. A text-to-picture app.

s.surbiks@gmail.com
